"""relationの修正

Revision ID: 057b36187304
Revises: ad53177d8788
Create Date: 2026-09-14 15:39:56.816937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057b36187304'
down_revision: Union[str, Sequence[str], None] = 'ad53177d8788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('commit_lines_commit_id_fkey'), 'commit_lines', type_='foreignkey')
    op.drop_constraint(op.f('commit_lines_parent_id_fkey'), 'commit_lines', type_='foreignkey')
    op.create_foreign_key(None, 'commit_lines', 'commit_lines', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'commit_lines', 'commits', ['commit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commit_lines', type_='foreignkey')
    op.drop_constraint(None, 'commit_lines', type_='foreignkey')
    op.create_foreign_key(op.f('commit_lines_parent_id_fkey'), 'commit_lines', 'lines', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('commit_lines_commit_id_fkey'), 'commit_lines', 'commit_lines', ['commit_id'], ['id'])
    # ### end Alembic commands ###
