"""create users table

Revision ID: 6ca97fc0ed55
Revises: 
Create Date: 2026-08-20 18:19:28.591292

"""
from typing import Sequence, Union
import uuid
from sqlalchemy.dialects.postgresql import UUID

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca97fc0ed55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.create_table(
        'users',
        sa.Column(
            'id',
            UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            default=uuid.uuid4,
        ),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('hashed_password', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('usercode', sa.String(length=20), nullable=False),
    )
    op.create_index(
        op.f('ix_users_email'),
        'users',
        ['email'],
        unique=True,
    )

    op.create_table(
        'notes',
        sa.Column(
            'id',
            UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            default=uuid.uuid4,
        ),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('user_id', UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
